@startuml
'https://plantuml.com/class-diagram
class Component{}
class Container extends Component{}
class Panel extends Container{}
class Applet extends Panel{}
class JApplet extends Applet{}
class Program extends JApplet{}
class JComponent extends Container{}
class JPanel extends JComponent{}
class SwingInteractorClasses extends JComponent{}
class GCanvas extends Container{}
class IOConsole extends Container{}
class Window extends Container{}
class Frame extends Window{}
class JFrame extends Frame{}

@enduml